In [1]:
# Import necessary tools
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MultiLabelBinarizer
print("TF version:", tf.__version__)
# print("TF Hub version:", hub.__version__)

# Check for GPU availability
print("GPU", "available (YESSSS!!!!!)" if tf.config.list_physical_devices("GPU") else "not available :(")

TF version: 2.10.0
GPU available (YESSSS!!!!!)

In [2]:
# Read the CSVs
df = pd.read_csv("dataset.csv")
weights_df = pd.read_csv("Symptom-severity.csv")
precaution_df = pd.read_csv("symptom_precaution.csv")
description_df = pd.read_csv("symptom_Description.csv")

In [3]:
# Symptom and Weights (Severity)
weights_df.columns = [c.strip().lower() for c in weights_df.columns]   # e.g. ["symptom","weight"]
symptom_weights = dict(zip(weights_df["symptom"], weights_df["weight"]))

In [4]:
# Clean symptom strings in dataset
label_col    = df.columns[0]          # first col is the diagnosis label
symptom_cols = df.columns[1:]         # remaining cols are symptom slots

In [5]:
# Vectorised string clean‑up (no deprecated applymap):
df[symptom_cols] = (
    df[symptom_cols]
      .apply(lambda col: (
          col
            .astype(str)              # handle NaNs safely
            .str.strip()
            .str.lower()
            .str.replace(" ", "_", regex=False)
            .where(col.notna())       # restore NaNs where they were
      ))
)

In [6]:
# Skip Empty Values in the Dataset
df["symptoms"] = df[symptom_cols].apply(
    lambda row: [s for s in row if pd.notna(s)],
    axis=1
)

In [7]:
# One‑hot encode with scikit‑learn
mlb = MultiLabelBinarizer()
symptom_binary = pd.DataFrame(
    mlb.fit_transform(df["symptoms"]),
    columns=mlb.classes_,
    index=df.index
)

In [8]:
# Convert binary matrix to weighted matrix in one vectorised step
weight_series    = pd.Series(symptom_weights)
symptom_weighted = symptom_binary.mul(weight_series, axis=1).fillna(0)

In [9]:
# Concatenate with the label column
final_df = pd.concat(
    [symptom_weighted, df[[label_col]].rename(columns={label_col: "label"})],
    axis=1
)

In [10]:
final_df

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin,label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(vertigo) Paroymsal Positional Vertigo
4916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Acne
4917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Urinary tract infection
4918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Psoriasis
4919,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,Impetigo

In [11]:
weights_df.sort_values(by='symptom', inplace = True)

In [12]:
weights_df

                   symptom  weight
39          abdominal_pain       4
101  abnormal_menstruation       6
8                  acidity       3
44     acute_liver_failure       6
98       altered_sensorium       2
..                     ...     ...
19             weight_loss       3
131      yellow_crust_ooze       3
42            yellow_urine       4
43       yellowing_of_eyes       4
32          yellowish_skin       3

[133 rows x 2 columns]

In [13]:
precaution_df

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out
2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths
5,GERD,avoid fatty spicy food,avoid lying down after eating,maintain healthy weight,exercise
6,Chronic cholestasis,cold baths,anti itch medicine,consult doctor,eat healthy
7,hepatitis A,Consult nearest hospital,wash hands through,avoid fatty spicy food,medication
8,Osteoarthristis,acetaminophen,consult nearest hospital,follow up,salt baths
9,(vertigo) Paroymsal Positional Vertigo,lie down,avoid sudden change in body,avoid abrupt head movment,relax
10,Hypoglycemia,lie down on side,check in pulse,drink sugary drinks,consult doctor
11,Acne,bath twice,avoid fatty spicy food,drink plenty of water,avoid too many products
12,Diabetes,have balanced diet,exercise,consult doctor,follow up
13,Impetigo,soak affected area in warm water,use antibiotics,remove scabs with wet compressed cloth,consult doctor
14,Hypertension,meditation,salt baths,reduce stress,get proper sleep
15,Peptic ulcer diseae,avoid fatty spicy food,consume probiotic food,eliminate milk,limit alcohol
16,Dimorphic hemmorhoids(piles),avoid fatty spicy food,consume witch hazel,warm bath with epsom salt,consume alovera juice
17,Common Cold,drink vitamin c rich drinks,take vapour,avoid cold food,keep fever in check
18,Chicken pox,use neem in bathing,consume neem leaves,take vaccine,avoid public places
19,Cervical spondylosis,use heating pad or cold pack,exercise,take otc pain reliver,consult doctor
20,Hyperthyroidism,eat healthy,massage,use lemon balm,take radioactive iodine treatment
21,Urinary tract infection,drink plenty of water,increase vitamin c intake,drink cranberry juice,take probiotics
22,Varicose veins,lie down flat and raise the leg high,use oinments,use vein compression,dont stand still for long
23,AIDS,avoid open cuts,wear ppe if possible,consult doctor,follow up
24,Paralysis (brain hemorrhage),massage,eat healthy,exercise,consult doctor
25,Typhoid,eat high calorie vegitables,antiboitic therapy,consult doctor,medication
26,Hepatitis B,consult nearest hospital,vaccination,eat healthy,medication
27,Fungal infection,bath twice,use detol or neem in bathing water,keep infected area dry,use clean cloths
28,Hepatitis C,Consult nearest hospital,vaccination,eat healthy,medication
29,Migraine,meditation,reduce stress,use poloroid glasses in sun,consult doctor
30,Bronchial Asthma,switch to loose cloothing,take deep breaths,get away from trigger,seek help
31,Alcoholic hepatitis,stop alcohol consumption,consult doctor,medication,follow up
32,Jaundice,drink plenty of water,consume milk thistle,eat fruits and high fiberous food,medication
33,Hepatitis E,stop alcohol consumption,rest,consult doctor,medication
34,Dengue,drink papaya leaf juice,avoid fatty spicy food,keep mosquitos away,keep hydrated
35,Hepatitis D,consult doctor,medication,eat healthy,follow up
36,Heart attack,call ambulance,chew or swallow asprin,keep calm,NaN
37,Pneumonia,consult doctor,medication,rest,follow up
38,Arthritis,exercise,use hot and cold therapy,try acupuncture,massage
39,Gastroenteritis,stop eating solid food for while,try taking small sips of water,rest,ease back into eating
40,Tuberculosis,cover mouth,consult doctor,medication,rest

In [14]:
description_df

,Disease,Description
0,Drug Reaction,An adverse drug reaction (ADR) is an injury ca...
1,Malaria,An infectious disease caused by protozoan para...
2,Allergy,An allergy is an immune system response to a f...
3,Hypothyroidism,"Hypothyroidism, also called underactive thyroi..."
4,Psoriasis,Psoriasis is a common skin disorder that forms...
5,GERD,"Gastroesophageal reflux disease, or GERD, is a..."
6,Chronic cholestasis,"Chronic cholestatic diseases, whether occurrin..."
7,hepatitis A,Hepatitis A is a highly contagious liver infec...
8,Osteoarthristis,Osteoarthritis is the most common form of arth...
9,(vertigo) Paroymsal Positional Vertigo,Benign paroxysmal positional vertigo (BPPV) is...
10,Hypoglycemia,Hypoglycemia is a condition in which your blo...
11,Acne,"Acne vulgaris is the formation of comedones, p..."
12,Diabetes,Diabetes is a disease that occurs when your bl...
13,Impetigo,Impetigo (im-puh-TIE-go) is a common and highl...
14,Hypertension,"Hypertension (HTN or HT), also known as high b..."
15,Peptic ulcer diseae,Peptic ulcer disease (PUD) is a break in the i...
16,Dimorphic hemorrhoids(piles),"Hemorrhoids, also spelled haemorrhoids, are va..."
17,Common Cold,The common cold is a viral infection of your n...
18,Chicken pox,Chickenpox is a highly contagious disease caus...
19,Cervical spondylosis,Cervical spondylosis is a general term for age...
20,Hyperthyroidism,Hyperthyroidism (overactive thyroid) occurs wh...
21,Urinary tract infection,Urinary tract infection: An infection of the k...
22,Varicose veins,"A vein that has enlarged and twisted, often ap..."
23,AIDS,Acquired immunodeficiency syndrome (AIDS) is a...
24,Paralysis (brain hemorrhage),Intracerebral hemorrhage (ICH) is when blood s...
25,Typhoid,An acute illness characterized by fever caused...
26,Hepatitis B,Hepatitis B is an infection of your liver. It ...
27,Fungal infection,"In humans, fungal infections occur when an inv..."
28,Hepatitis C,Inflammation of the liver due to the hepatitis...
29,Migraine,A migraine can cause severe throbbing pain or ...
30,Bronchial Asthma,Bronchial asthma is a medical condition which ...
31,Alcoholic hepatitis,"Alcoholic hepatitis is a diseased, inflammator..."
32,Jaundice,Yellow staining of the skin and sclerae (the w...
33,Hepatitis E,A rare form of liver inflammation caused by in...
34,Dengue,an acute infectious disease caused by a flaviv...
35,Hepatitis D,"Hepatitis D, also known as the hepatitis delta..."
36,Heart attack,The death of heart muscle due to the loss of b...
37,Pneumonia,Pneumonia is an infection in one or both lungs...
38,Arthritis,Arthritis is the swelling and tenderness of on...
39,Gastroenteritis,Gastroenteritis is an inflammation of the dige...
40,Tuberculosis,Tuberculosis (TB) is an infectious disease usu...

In [15]:
final_df.columns.to_list()[32]

'dischromic__patches'

In [16]:
final_df.columns.to_list()[33]

'dischromic_patches'

In [17]:
final_df.drop("dischromic__patches", axis = 1, inplace = True)

In [18]:
final_df

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin,label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(vertigo) Paroymsal Positional Vertigo
4916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Acne
4917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Urinary tract infection
4918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Psoriasis
4919,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,Impetigo

In [19]:
final_df.columns.to_list()[106]

'spotting__urination'

In [20]:
final_df.columns.to_list()[107]

'spotting_urination'

In [21]:
final_df.drop("spotting__urination", axis = 1, inplace = True)

In [22]:
final_df

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin,label
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(vertigo) Paroymsal Positional Vertigo
4916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Acne
4917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Urinary tract infection
4918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Psoriasis
4919,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,Impetigo

In [23]:
# Save the result
final_df.to_csv("final_weighted_dataset.csv", index=False)